FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y \
        openjdk-8-jdk \
        python3 \
        scala \
        curl \
        vim && \
    mkdir /opt/sbt && \
    curl -L -o /opt/sbt/sbt.tgz https://github.com/sbt/sbt/releases/download/v1.11.7/sbt-1.11.7.tgz && \
    tar -xzf /opt/sbt/sbt.tgz -C /opt/sbt --strip-components=1 && \
    rm /opt/sbt/sbt.tgz && \
    rm -rf /var/lib/apt/lists/*

ENV PATH="/opt/sbt/bin:${PATH}"

CMD ["/bin/bash"]