FROM ubuntu:24:04

RUN apt-get update && apt-get install -y openjdk-8-jdk

RUN apt-get install -y python3 

RUN apt-get install -y scala 

RUN scala --version

RUN python3 --version

RUN javac -version

