### POST 3.0
POST http://localhost:8080/tail
Content-Type: application/json

{
  "inputList": [7, 65, 3, 54, 1, 8, 0, 210]
}
### POST 3.5
POST http://localhost:8080/drop
Content-Type: application/json

{
  "inputList": [7, 65, 3, 54, 1, 8, 0, 210],
  "n": 2
}
### POST 4.0
POST http://localhost:8080/dropWhile
Content-Type: application/json

{
  "inputList": [7, 65, 3, 54, 1, 8, 0, 210],
  "condition": "< 100"
}
### POST 4.5
POST http://localhost:8080/foldLeft
Content-Type: application/json

{
  "inputList": [7, 65, 3, 54, 1, 8, 0, 210]
}
### POST 5.0
POST http://localhost:8080/concatenate
Content-Type: application/json

{
  "inputList1": [7, 65, 3, 54, 1, 8, 0, 210],
  "inputList2": [87, 4, 5, 34, 66, 3, 7, 9]
}
