###
POST http://localhost:8080/is-sorted
Content-Type: application/json

{
  "nums": [7, 65, 3, 54, 1, 8, 0, 210]
}
###
POST http://localhost:8080/sum-three
Content-Type: application/json

{
  "list1": [7, 65, 3, 54, 1, 8, 0, 210],
  "list2": [2, 5, 31, 43, 16, 98, 1000, 10],
  "list3": [11, 9, 2, 5, 4, 5, 70, 21]
}
###
GET http://localhost:8080/is-sorted
###